title: Maksadbek's blog
email: a.maksadbek@gmail.com
description: >-
  This is my personal blog, articles are mostly about the things that I did not understand before, that is why I explored them and wrote an article.
baseurl: ""
url: "http://maksadbek.github.io"
twitter_username: maksadbek_a
github_username:  maksadbek

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
